#!/usr/bin/env python3

#IOT LoRa Installer
#By Ryan Walmsley
#This file downloads the current software for the LoRa Gateway Packet Forwarder By Kersing and installs it on your Raspberry Pi
#At the same time it also enables SPI, Installs a service to automatically start it on boot, a configuration script and
#Sets the core clock to a fixed frequency which fixes bugs on Models 3B & 3B+

#This Software is designed to be run on a Vanilla installation of Raspbian! We cannot gaurantee that it will not break Other
#Software you are running on your Raspberry Pi.

##Imports!
from time import sleep
import os, sys
##End imports

##START
print ('''

  ___ ___ _____   _        ___         ___      _
 |_ _/ _ \_   _| | |   ___| _ \__ _   / __|__ _| |_ _____ __ ____ _ _  _
  | | (_) || |   | |__/ _ \   / _` | | (_ / _` |  _/ -_) V  V / _` | || |
 |___\___/ |_|   |____\___/_|_\__,_|  \___\__,_|\__\___|\_/\_/\__,_|\_, |
                                                                    |__/

This script will install the software required to get your Pi Supply
IoT Lora Gateway HAT Up and running with The Things Network
The script will automatically continue in 10 seconds. If you are not happy press Control + C to quit.
''')
sleep(10)

##TODO
##We need to check which system this is running on

#Set variable model to
#Expected results:
#RPi : Raspberry
#Odroid C2: ODROID-C2
#Tinkerboard: Rockchip
#Unknown: 42

try:
    dtModel = open('/proc/device-tree/model','r')
except:
    print("Device Tree directory not found, this is likely because you are running this program on a normal computer or a non supported SBC")
    exit()
modelUsed = dtModel.read().split(" ")[0]
print ("Detected SBC: %s" %modelUsed)



##Update Apt Repo List, Upgrade Any Other Packages and then install the required Packages
os.system("apt-get update && apt-get upgrade -y && apt-get install python3-dialog protobuf-compiler libprotobuf-dev libprotoc-dev automake libtool autoconf git pkg-config protobuf-c-compiler -y")

##Delete all of the old softwar,e this is fine as the configuration files are stored on the /boot partition
os.system("rm -rf /opt/iotloragateway")
##Remake the directory structure
os.system("mkdir -p /opt/iotloragateway")
os.system("mkdir -p /opt/iotloragateway/dev")

##Download all fo the software required
os.chdir("/opt/iotloragateway/dev")
os.system("git clone https://github.com/PiSupply/lora_gateway.git")
os.system("git clone https://github.com/PiSupply/paho.mqtt.embedded-c.git")
os.system("git clone https://github.com/PiSupply/ttn-gateway-connector.git")
os.system("git clone https://github.com/PiSupply/protobuf-c.git")
os.system("git clone https://github.com/PiSupply/packet_forwarder.git")
os.system("git clone https://github.com/PiSupply/iot-lora-gateway.git")
##First lets compile the LoRa Gateway driver library which provides the SPI Interface

##Change the configuration file based on what system is being used.

##Compile the gateway driver

##Move to the Protobuf-c library and compile it


##Install the library

##Move to the MQTT Embedded library


##Move to the TTN Connector library

##Copy it to the /usr/lib directory for usage

#Move to the packet forwarder itself

##Compile it

##And move this up one directory for the user to run

#Move to the directory with all of our template configuration files

#Create folders on the SD Card's boot, this will get ignored if it all exsists

#Copy all of the template files over

#Copy over the local config files

#And copy over the service files

#Cppy over the correct reset script into the /opt directory

##if raspberry Pi enable the SPI bus and set the core clock to 250mhz

##Reload systemctl daemon and enable the service

##Symlink the configuration python file so the user can run it from the terminal

print('''
  ___ ___ _____   _        ___         ___      _
 |_ _/ _ \_   _| | |   ___| _ \__ _   / __|__ _| |_ _____ __ ____ _ _  _
  | | (_) || |   | |__/ _ \   / _` | | (_ / _` |  _/ -_) V  V / _` | || |
 |___\___/ |_|   |____\___/_|_\__,_|  \___\__,_|\__\___|\_/\_/\__,_|\_, |
                                                                    |__/

Congratulations the gateway software is now fully installed!

You need to edit the configuration file for your gateway to be setup which is located
at /boot/iotloragateway/

You can either do this using a text editor or run "iot-lora-configure" for our
wizard based editor.

After upon rebooting your Raspberry Pi your gateway should be up and running.

''')

#File end
